# Basic Information 
title: Jie Lu
position: Ph.D. Student
affiliation: Michigan State University (MSU)
affiliation_link: https://msu.edu/
email: lujie2 [at] msu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: "jie lu, msu, phd, wireless, 5g, 6g, nr, oran, o-ran, reinforcement learning"
description: Personal Website of Jie Lu, a CS Ph.D. student at Michigan State University researching AI-driven wireless networking systems.
canonical: https://jadejavu.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=Qp9bMGIAAAAJ&hl=en
cv_link: assets/files/JieLu_Resume_Web.pdf
#github_link: https://github.com/
linkedin: https://www.linkedin.com/in/jie-lu-2791a4324/
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
#enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-3730J71LXR

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
